name: Trigger auto deployment for my-web-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/my-web-app-AutoDeployTrigger-ca72ed95-2a29-48e3-9c6a-95ab51c5910d.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MYWEBAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: cab6fa743d3dacr.azurecr.io
          registryUsername: ${{ secrets.MYWEBAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MYWEBAPP_REGISTRY_PASSWORD }}
          containerAppName: my-web-app
          resourceGroup: my-web-app-aca-rg
          imageToBuild: cab6fa743d3dacr.azurecr.io/my-web-app:${{ github.sha }}
          
            

     

